title: "[General] "
labels: ["General Introduction"]
body:
  - type: input
    id: decision
    attributes:
      label: Decision
      description: Short title of solved problem and solution
  - type: textarea
    id: problem
    attributes:
      label: Context and Problem Statement
      description: "Describe the context and problem statement, e.g., in free form using two to three sentences or in the form of an illustrative story. You may want to articulate the problem in form of a question and add links to collaboration boards or issue management systems."
      render: bash
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Considered Options
      description: "What are the top 3 improvements we could make to this project?"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: decision
    attributes:
      label: Decision Outcome
      description: "justification. e.g., only option, which meets k.o. criterion decision driver | which resolves force {force} | … | comes out best (see below)"
      value: |
        Chosen option: "{title of option 1}", because....
      render: bash
    validations:
      required: true
