title: "[Décision] "
body:
  - type: markdown
    id: decision
    attributes:
      value: |
        :point_up: Titre court du problème résolu et de la solution
  - type: textarea
    id: problem
    attributes:
      label: Contexte et description du problème
      description: "Décrivez le contexte et l'énoncé du problème, p. ex. en utilisant deux ou trois phrases ou sous la forme d'une histoire illustrative. Vous pouvez également articuler le problème sous forme de question et ajouter des liens vers des tableaux de collaboration ou des systèmes de gestion des problèmes."
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Options considérées
      description: "Quelles sont les options envisagées pour régler le problème? Év. quels sont les avantages et inconvénients de chacune?"
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Résultat de la décision
      description: "Notez l'option retenue et justifiez-en la raison."
      value: |
        Options retenue: Option X -> titre de l'option X. Nous avons retenu cette options car...
    validations:
      required: true
